project:
  type: website
  output-dir: docs

website:
  title: "Laboratory of Quantitative Ecology"
  
  description: website of LoQE, Faculty of Science, Charles University."

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  site-url: "https://loqe-cuni.github.io/"
  repo-url: "https://github.com/LOQE-CUNI/LOQE-CUNI.github.io"
  issue-url: "https://github.com/LOQE-CUNI/LOQE-CUNI.github.io/issues"
  repo-actions: source
  
  favicon: Materials/Logos/lab_logo_nobg.png
  image: Materials/Logos/lab_logo_nobg.png

  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    left:
      - text: Activities
        href: activities.qmd

      - text: Team
        href: Team.qmd

      - text: Outputs
        href: outputs.qmd

    
format:
  html:
    theme:
      - custom_style.scss 
    toc: false



